name: w-R-CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.0'  # 指定 R 版本为 4.4.0

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("ggpubr", "corrplot", "glmnet", "caret", "CBCgrps", "tidyverse", "rms", "pROC", "readxl", "tableone", "this.path", "parallel", "foreach", "doParallel", "writexl", "doSNOW"))'

    - name: Run R script
      run: |
        Rscript LASSO_plus_parallel.R

    - name: Upload CSV file
      uses: actions/upload-artifact@v3
      with:
        name: result-csv
        path: feature_selection_results.csv  # 请将其替换为你的 CSV 文件的实际路径
